apiVersion: v1
kind: Service
metadata:
  name: sslservice2-service
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    pod-app: sslservice2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sslservice2-deployment
  labels:
    app: sslservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-app: sslservice2
  template:
    metadata:
      labels:
        pod-app: sslservice2
    spec:
      containers:
      - name: sslservice2-container
        image: cr2019.azurecr.io/sslservice2:latest
